rides/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('rides.views',
    url(r'^$', 'index', name='rides'),
    url(r'^(?P<id>(\d+))/$', 'details'),
    url(r'^(?P<id>(\d+))/(?P<slug>(.+))/$', 'details'),
)

sales/urls.py
from django.conf.urls import *
from sales import views
 
urlpatterns = patterns('sales.views',
    url(r'^checkout/(?P<ride_id>\d+)/$', 'checkout', name='checkout'),
    url(r'^terms/(?P<ride_id>\d+)/$', 'terms', name='terms')
)

sales/models.py
import stripe
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

class Sale(models.Model):
    sale_date   = models.DateTimeField(default=datetime.now())
    charge_id   = models.CharField(max_length=32) # store the stripe charge id for this sale
    amount      = models.IntegerField(max_length=6, null=True, blank=True)
    currency    = models.CharField(max_length = 3, choices=(('gbp', 'GBP'), ('usd', 'USD'), ('eur', 'EUR')), default = 'gbp')
    livemode    = models.BooleanField()
    card        = models.CharField(blank=True, null=True, max_length=255)
    # also store the rider id
    rider       = models.ForeignKey(User)

    def __init__(self, *args, **kwargs):
        super(Sale, self).__init__(*args, **kwargs)

    def __unicode__(self):
        return self.charge_id

    @classmethod
    def charge(cls, user, ride, token):
        """
        Takes a the price and a Stripe token.
 
        Raises a stripe.CardError on errors.
        """

        instance = cls()

        stripe.api_key = ride.chapter.get_priv_key()

        try:
            response = stripe.Charge.create(
                amount = int(ride.price * 100), # in cents
                currency = ride.currency,
                card = token,
                receipt_email = user.email,
                description = "{}: {}".format(ride.name, user.email))
        except stripe.CardError:
            raise # Just be explicit about what we are raising

        instance.charge_id = response.id
        instance.amount = response.amount
        instance.currency = response.currency
        instance.livemode = response.livemode
        instance.card = response.card.id
        instance.rider_id = user.id
 
        return instance
        
    class Meta:
        db_table    = 'sales'
        app_label   = 'sales'

sales/forms.py
from django import forms

from rides.models import Ride

class RideCheckoutForm(forms.Form):
    stripe_token = forms.CharField(widget=forms.HiddenInput())
    tnc = forms.BooleanField(
        error_messages={'required': 'Please accept our Terms and Conditions.'}
    )

sales/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST, require_GET
from django.contrib.auth.decorators import login_required
from django.conf import settings

from rides.models import Ride, RideRiders
from sales.models import Sale
from sales.forms import RideCheckoutForm

import stripe

@login_required()
def checkout(request, ride_id):
    try:
        # Get the ride info
        ride = Ride.objects.get(id = ride_id)
    except Ride.DoesNotExist:
        return render(request, 'sales/error.html', {'error': "You did not specify a ride!"})

    if request.method == "POST":
        form = RideCheckoutForm(request.POST)
    else:
        form = RideCheckoutForm()

    # If the user has the secret key then they can register regardless of spaces left
    has_sales_key = request.GET.get('key', None) == settings.SECRET_SALES_KEY
    full = ride.spaces_left < 1 and not has_sales_key

    variables  = {
        'ride': ride,
        'form': form,
        'signed_up': False,
        'full': full
    }

    # Check to see if the rider is already signed up to this ride
    # There must be a better way of doing this
    try:
        ride.rideriders_set.get(user = request.user)
        variables['signed_up'] = True
    except RideRiders.DoesNotExist:
        pass

    if not full and request.method == "POST" and form.is_valid():
        token = form.cleaned_data['stripe_token']

        try:
            sale = Sale.charge(request.user, ride, token)
            sale.save()
        except stripe.CardError:
            return render(request, 'sales/error.html',
                {'error': 'Something went wrong when processing your payment. Please get in touch with us!'})

        # So we've now successfully charged the user so lets make sure they are
        # signed up to the ride
        ride_rider = RideRiders()
        ride_rider.user = request.user
        ride_rider.ride = ride
        ride_rider.paid = True
        ride_rider.sale = sale
        ride_rider.save()

        return render(request, 'sales/success.html', {'ride': ride})
    else:
        return render(request, 'sales/checkout.html', variables)

@login_required
def terms(request, ride_id):
    try:
        # Get the ride info
        ride = Ride.objects.get(id = ride_id)
    except Ride.DoesNotExist:
        return render(request, 'sales/error.html', {'error': "You did not specify a ride!"})

    return render(request, 'sales/terms.html', {'ride': ride})

templates/sales/checkout.html
{% extends "shared/_base.html" %}

{% load currency %}
{% load staticfiles %}

{% block head %}
<!-- The required Stripe lib -->
<script type="text/javascript" src="https://js.stripe.com/v1/"></script>
{% endblock %}

{% block content %}
<div class="content">

    {% if not form.stripe_token.value %}
    <script type="text/javascript">
        // This identifies your website in the createToken call below
        Stripe.setPublishableKey('{{ ride.chapter.get_pub_key }}');

        var stripeResponseHandler = function(status, response) {
          var $form = $('#payment-form');

          if (response.error) {
            // Show the errors on the form
            $form.find('.field-validation-error').text(response.error.message);
            $form.find('button').prop('disabled', false);
          } else {
            // token contains id, last4, and card type
            var token = response.id;
            // Insert the token into the form so it gets submitted to the server
            $form.find('#id_stripe_token').val(token);
            // and re-submit
            $form.get(0).submit();
          }
        };

        jQuery(function($) {
          $('#payment-form').submit(function(e) {
            var $form = $(this);

            // Disable the submit button to prevent repeated clicks
            $form.find('button').prop('disabled', true);

            Stripe.createToken($form, stripeResponseHandler);

            // Prevent the form from submitting with the default action
            return false;
          });
        });
    </script>
    {% endif %}

  <section>
    <header>
      <h1>Register for {{ ride.name }}</h1>
    </header>

    {% if signed_up %}

    <p>
        You have already signed up for the {{ ride.name }} ride. No need to pay for it again!
    </p>

    {% elif full %}

    <p>
        Dang... This ride is full! <a href='https://docs.google.com/forms/d/1q1pNgvnQ3Mf9yeecb6A27dcAwL0Ds88Je8xVn5lVBVA/viewform'>Add yourself to the waitlist</a> and we'll let you know if a slot becomes available.
    </p>

    {% else %}

    <ol class="steps">
      <li>
        <span>1</span>
        <span>Join Techbikers</span>
      </li>

      <li class="active">
        <span>2</span>
        <span>Pay the ride fee</span>
      </li>

      <li>
        <span>3</span>
        <span>Registration Complete!</span>
      </li>
    </ol>

    <p class="centerText">
        You are about to sign up for <strong>{{ ride.name }}</strong> at a cost of <strong>{{ ride.currency|upper }} {{ ride.price|floatformat:2 }}</strong>.<br/>
    </p>

    <form method="POST" id="payment-form">
        <span class="field-validation-error centerText">{{ form.non_field_errors }}</span>

        {% csrf_token %}
        <input type="hidden" name="NO_CHROME" value="{{ NO_CHROME }}">

        {{ form.stripe_token }}

        {% if not form.stripe_token.value %}
        <div class="creditCard">

            <div class="infoRow">
                <img src="{% static "img/icons/amex.png" %}" />
                <img src="{% static "img/icons/diners.png" %}" />
                <img src="{% static "img/icons/discover.png" %}" />
                <img src="{% static "img/icons/jcb.png" %}" />
                <img src="{% static "img/icons/mastercard.png" %}" />
                <img src="{% static "img/icons/visa.png" %}" />
            </div>

            <div class="topRow">
                <input class="longNumber" type="text" size="20" data-stripe="number" placeholder="XXXX XXXX XXXX XXXX"/>
                <input class="cvc" type="text" size="20" data-stripe="cvc" placeholder="CVC" />
            </div>

            <div class="bottomRow">
                <input class="nameOnCard" type="text" size="20" data-stripe="name" placeholder="Name on card"/>

                <div class="date">
                    <input class="month" type="text" size="2" data-stripe="exp-month" placeholder="MM"/>
                    <input class="year" type="text" size="4" data-stripe="exp-year" placeholder="YYYY"/>
                </div>
            </div>
        </div>
        {% endif %}

        {% if 'tnc' in form.fields %}
        {% for error in form.tnc.errors %}
        <p class="field-validation-error centerText">{{ error }}</p>
        {% endfor %}
        <p class="centerText">
            {{ form.tnc }}
            <label for="id_tnc">I agree to the <a href="{% url 'sales.views.terms' ride.id %}">Terms and Conditions</a> of this ride.</label>
        </p>
        {% endif %}

        <p class="centerText">
            <input class="btn" type="submit" value="Charge my card {{ ride.currency|upper }} {{ ride.price|floatformat:2 }}" />
        </p>
    </form>

    <p class="centerText">
        <a href="https://www.stripe.com" target="_blank"><img src="{% static 'img/stripe@2x.png' %}" alt="Stripe supports TechBikers"  width="160px"/></a>
        <br/>
        <small>Payments powered by Stripe - the easy way to take card payments online.</small>
    </p>


    {% endif %}
  </section>
</div>

{% endblock %}

templates/sales/error.html
{% extends "shared/_base.html" %}

{% block content %}
<div class="content">
    <section>
        <header>
            <h1>Something went wrong</h1>
        </header>

        <p>
            Unfortunately we haven't been able to process your payment because of the reason stated below.
            You have not been charged and as a result have not been signed up to the ride.
            If the problem persists or you have any questions then get in touch.
        </p>

        <p>
            {{ error }}
        </p>

    </section>
</div>
{% endblock %}

templates/sales/success.html
{% extends "shared/_base.html" %}

{% load staticfiles %}

{% block content %}

<div class="content">
  <section>
    <header>
      <h1>You are Registered for {{ ride.name }}!</h1>
    </header>

    <ol class="steps">
      <li>
        <span>1</span>
        <span>Join Techbikers</span>
      </li>

      <li>
        <span>2</span>
        <span>Pay the ride fee</span>
      </li>

      <li class="active">
        <span>3</span>
        <span>Registration Complete!</span>
      </li>
    </ol>

    <p>
      We have successfully charged your card and signed you up for the ride. Time to get fundraising!
    </p>

{% comment %}
    <h2>Now it’s time to start your fundraising for Room to Read.</h2>

    <p>
      Believe.in is part of the London startup community and is proud to power donations and fundraising for TechBikers and Room to Read. With Believe.in 100% of every donation and 100% of Gift Aid goes directly to charity. Set up your fundraiser now using the link below to be added to the TechBikers event page and to see how much the team can raise!
    </p>

    <p class="centerText">
      <a href="https://believe.in/fundraising/start?event_id=1&amount=60000" target="_blank">
        <img src="{% static 'img/believeinShot.jpg' %}" alt="TechBikers on Belive.in" />
      </a>
    </p>

    <p class="centerText">
      <a class="btn" href="https://believe.in/fundraising/start?event_id=1&amount=60000" target="_blank">Get me setup to fundraise!</a>
    </p>
{% endcomment %}

  </section>
</div>

{% endblock %}

templates/sales/terms.html
{% extends "shared/_base.html" %}

{% load currency %}
{% load staticfiles %}
{% load markup %}

{% block title %}Terms and Conditions for the {{ride.name}} ride{% endblock %}

{% block content %}
<div class="content">
    <h1>Terms and Conditions ({{ ride.name }})</h1>
    {{ ride.terms_and_conditions|markdown:"safe" }}
</div>
{% endblock %}